const express = require('express');
const router = express.Router();

// Import route modules
const userRoutes = require('./user/user.route.js');
const roleRoutes = require('./admin/role.route.js');
const responsibilityRoutes = require('./admin/responsibility.route.js');
const languageRoutes = require('./admin/language.route.js');
const countryRoutes = require('./admin/country.route.js');
const stateRoutes = require('./admin/state.route.js');
const cityRoutes = require('./admin/city.route.js');
const itemsTypesRoutes = require('./admin/items_types.route.js');
const itemsRoutes = require('./admin/items.route.js');
const floorTypeRoutes = require('./admin/floor_type.route.js');
const floorRoutes = require('./admin/floor.route.js');
const tableTypesRoutes = require('./admin/table_types.route.js');
const tableBookingStatusRoutes = require('./admin/table_booking_status.route.js');
const tableRoutes = require('./admin/table.route.js');
const otpRoutes = require('./admin/otp.route.js');
const customerTypeRoutes = require('./admin/customer_type.route.js');
const clientsRoutes = require('./admin/clients.route.js');
const auditsRoutes = require('./admin/audits.route.js');
const paymentsRoutes = require('./admin/payments.route.js');
const businessSettingsRoutes = require('./admin/business_settings.route.js');
const subAdminPermissionsRoutes = require('./admin/subadmin_permissions.route.js');
const adminPlanRoutes = require('./admin/admin_plan.route.js');
const reportsRoutes = require('./restaurant/reports.route.js');
const quickOrderRoutes = require('./employee/quick_order.route.js');
const tableBookingRoutes = require('./employee/table_booking.route.js');
const orderHistoryRoutes = require('./employee/order_history.route.js');
const notificationsRoutes = require('./master/notifications.route.js');
const notificationsMapEmployeeRoutes = require('./master/notifications_map_employee.route.js');
const clockRoutes = require('./master/clock.route.js');
const faqRoutes = require('./master/faq.route.js');
const feedbackTypeRoutes = require('./master/feedback_type.route.js');
const feedbackRoutes = require('./master/feedback.route.js');
const reviewTypeRoutes = require('./master/review_type.route.js');
const reviewRoutes = require('./master/review.route.js');
const myDevicesRoutes = require('./master/myDevices.route.js');
const currencyRoutes = require('./master/currency.route.js');
const planRoutes = require('./master/plan.route.js');
const planMapClientRoutes = require('./master/plan_map_client.route.js');
const floorMapTableRoutes = require('./master/floor_map_table.route.js');
const walletRoutes = require('./master/wallet.route.js');
const transactionRoutes = require('./master/transaction.route.js');

// Restaurant routes
const itemVariantsRoutes = require('./restaurant/item_Variants.route.js');
const itemAddonsRoutes = require('./restaurant/item_Addons.route.js');
const itemMapVariantsRoutes = require('./restaurant/item_map_Variants.route.js');
const itemMapAddonsRoutes = require('./restaurant/item_map_Addons.route.js');
const kitchenTypeRoutes = require('./restaurant/Kitchen_type.route.js');
const kitchenRoutes = require('./restaurant/Kitchen.route.js');
const customerRoutes = require('./restaurant/customer.route.js');
const posOrderRoutes = require('./restaurant/pos-order.route.js');
const reservationsRoutes = require('./restaurant/reservations.route.js');
const deliveryTypeRoutes = require('./restaurant/delivery_type.route.js');
const tokensRoutes = require('./restaurant/tokens.route.js');
const invoicesRoutes = require('./restaurant/invoices.route.js');
const permissionsTypeRoutes = require('./restaurant/permissions_type.route.js');
const permissionsTypeMapWithEmployeeRoutes = require('./restaurant/permissions_type_map_with_employee.route.js');
const restaurantReportsRoutes = require('./restaurant/reports.route.js');
const storeDetailsRoutes = require('./restaurant/store_details.route.js');
const printSettingsRoutes = require('./restaurant/print_settings.route.js');
const storeMenuRoutes = require('./restaurant/store_menu.route.js');
const menuMapItemsRoutes = require('./restaurant/menu_map_items.route.js');
const taxSetupRoutes = require('./restaurant/tax_setup.route.js');
const paymentTypeRoutes = require('./restaurant/payment_type.route.js');
const supportTicketTypeRoutes = require('./restaurant/support_ticket_type.route.js');
const supportTicketRoutes = require('./restaurant/support_ticket.route.js');
const supportTicketReplyRoutes = require('./restaurant/support_ticket_reply.route.js');
const restaurantSlotRoutes = require('./restaurant/restaurant_slot.route.js');
const adminPlanBuyRestaurantRoutes = require('./restaurant/admin_plan_buy_restaurant.route.js');
const jsonFileRoutes = require('./user/jsonFile.route.js');
const fileuploadRoutes = require('./fileupload.js');

// Use routes
router.use('/user', userRoutes);
router.use('/admin/role', roleRoutes);
router.use('/admin/responsibility', responsibilityRoutes);
router.use('/admin/language', languageRoutes);
router.use('/admin/country', countryRoutes);
router.use('/admin/state', stateRoutes);
router.use('/admin/city', cityRoutes);
router.use('/admin/items_types', itemsTypesRoutes);
router.use('/admin/items', itemsRoutes);
router.use('/admin/floor_type', floorTypeRoutes);
router.use('/admin/floor', floorRoutes);
router.use('/admin/table_types', tableTypesRoutes);
router.use('/admin/table_booking_status', tableBookingStatusRoutes);
router.use('/admin/table', tableRoutes);
router.use('/admin/otp', otpRoutes);
router.use('/admin/customer_type', customerTypeRoutes);
router.use('/admin/clients', clientsRoutes);
router.use('/admin/audits', auditsRoutes);
router.use('/admin/payments', paymentsRoutes);
router.use('/admin/business_settings', businessSettingsRoutes);
router.use('/admin/subadmin_permissions', subAdminPermissionsRoutes);
router.use('/admin/admin_plan', adminPlanRoutes);
router.use('/admin/reports', reportsRoutes);
router.use('/employee/quick_order', quickOrderRoutes);
router.use('/master/notifications', notificationsRoutes);
router.use('/master/notifications_map_employee', notificationsMapEmployeeRoutes);
router.use('/master/clock', clockRoutes);
router.use('/master/faq', faqRoutes);
router.use('/master/feedback_type', feedbackTypeRoutes);
router.use('/master/feedback', feedbackRoutes);
router.use('/master/review_type', reviewTypeRoutes);
router.use('/master/review', reviewRoutes);
router.use('/master/myDevices', myDevicesRoutes);
router.use('/master/currency', currencyRoutes);
router.use('/master/plan', planRoutes);
router.use('/master/plan_map_client', planMapClientRoutes);
router.use('/master/floor_map_table', floorMapTableRoutes);
router.use('/master/wallet', walletRoutes);
router.use('/master/transaction', transactionRoutes);
router.use('/employee/table_booking', tableBookingRoutes);
router.use('/employee/order_history', orderHistoryRoutes);

// Restaurant routes
router.use('/restaurant/item_variants', itemVariantsRoutes);
router.use('/restaurant/item_addons', itemAddonsRoutes);
router.use('/restaurant/item_map_variants', itemMapVariantsRoutes);
router.use('/restaurant/item_map_addons', itemMapAddonsRoutes);
router.use('/restaurant/kitchen_type', kitchenTypeRoutes);
router.use('/restaurant/kitchen', kitchenRoutes);
router.use('/restaurant/customer', customerRoutes);
router.use('/restaurant/pos_order', posOrderRoutes);
router.use('/restaurant/reservations', reservationsRoutes);
router.use('/restaurant/delivery_type', deliveryTypeRoutes);
router.use('/restaurant/tokens', tokensRoutes);
router.use('/restaurant/invoices', invoicesRoutes);
router.use('/restaurant/permissions_type', permissionsTypeRoutes);
router.use('/restaurant/permissions_type_map_with_employee', permissionsTypeMapWithEmployeeRoutes);
router.use('/restaurant/reports', restaurantReportsRoutes);
router.use('/restaurant/store_details', storeDetailsRoutes);
router.use('/restaurant/print_settings', printSettingsRoutes);
router.use('/restaurant/store_menu', storeMenuRoutes);
router.use('/restaurant/menu_map_items', menuMapItemsRoutes);
router.use('/restaurant/tax_setup', taxSetupRoutes);
router.use('/restaurant/payment_type', paymentTypeRoutes);
router.use('/restaurant/support_ticket_type', supportTicketTypeRoutes);
router.use('/restaurant/support_ticket', supportTicketRoutes);
router.use('/restaurant/support_ticket_reply', supportTicketReplyRoutes);
router.use('/restaurant/restaurant_slot', restaurantSlotRoutes);
router.use('/restaurant/admin_plan_buy_restaurant', adminPlanBuyRestaurantRoutes);
router.use('/user/jsonFile', jsonFileRoutes);
router.use('/fileupload', fileuploadRoutes);

module.exports = router;
